[package]
name = "wax"
version = "0.1.0"
edition = "2021"

[lib]
name = "_wax"
crate-type = ["cdylib"]

[lints.clippy]
all = { level = "deny", priority = -1 }

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module"] }
taffy = "0.9"
