[package]
name = "waxy"
version = "0.1.0"
edition = "2021"

[lib]
name = "_waxy"
crate-type = ["cdylib", "lib"]

[lints.clippy]
all = { level = "deny", priority = -1 }

[dependencies]
pyo3 = "0.28"
taffy = "0.9"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "style_merge"
harness = false
